### ISSUE TITLE
Validator2 gives a java.lang.OutOfMemoryError exception

### ISSUE THREAD

**Issue by jihonsvik** [difi/vefa-validator-conf#106]
Validator2 (http://vefa.difi.no/validator2/) gives an exception, I guess the problem is the size of the file (5332kb).
Can't attach the xml-file, but I can send it if necessary.
Screenshot of the exception with backtrace:
![validator2_exception](https://cloud.githubusercontent.com/assets/10721331/8869829/f824b37e-31e8-11e5-8bc7-92c0ae4dc5c0.JPG)

**Comment by klakegg** [comment]
This is not related to this repository.
