### ISSUE TITLE
Valdiation of CreditNote/cbc:ID is OK even with empty value. 

### ISSUE THREAD

**Issue by dagefjestad** [difi/vefa-validator-conf#107]
CreditNote without ID (kreditnotanummer) is validated OK. 
According to the guide as far I can see - it should not.

From the guide: 
Kreditnote 
CreditNote/cbc:ID 
Elementet må finnes A credit note MUST have a credit note identifier
BII2-T14-R003

**Comment by klakegg** [comment]
This is a matter of profile. Please send sample to ehf@difi.no.

**Comment by dagefjestad** [comment]
Image with ProfileID and CustomizationID:
![image](https://cloud.githubusercontent.com/assets/3918703/8976764/d5ddee72-3691-11e5-9718-4548498bc244.png)

**Comment by SiwMeckelborg** [comment]
Empty elements currently only raises a warning. This will be changed to an error in the revision released 1. october (2.0.5)
