### ISSUE TITLE
BII2-T10-R056 rule fires an error if one of the totals contains ".00"

### ISSUE THREAD

**Issue by cdruschk** [difi/vefa-validator-conf#111]
I saw first issue #109 and commented there as well, but since that one is closed I am opening a new one. 

When I have no decimal values in my invoice at all but in /ns:Invoice/cac:LegalMonetaryTotal/cbc:PayableAmount for some reason I have an amount with ".00" as decimals then the rule BII2-T10-R056 is firing an error. 

Example: 

 ' <cac:LegalMonetaryTotal>
 '   <cbc:LineExtensionAmount currencyID="NOK">65280</cbc:LineExtensionAmount>
 '   <cbc:TaxExclusiveAmount currencyID="NOK">65280</cbc:TaxExclusiveAmount>
 '   <cbc:TaxInclusiveAmount currencyID="NOK">81600</cbc:TaxInclusiveAmount>
 '   <cbc:PayableAmount currencyID="NOK">81600.00</cbc:PayableAmount>
'  </cac:LegalMonetaryTotal>

If I just remove the ".00" then I don´t get an error. 

This should be validating fine from business perspective, but it is generating an error and would stop the invoice.

**Comment by SiwMeckelborg** [comment]
could you please send the test-file to siw.meckelborg@edisys.no

**Comment by cdruschk** [comment]
I sent you the file via email now.

**Comment by SiwMeckelborg** [comment]
Error reported to PEPPOL Development team.
