### ISSUE TITLE
Bug in  BII2-T10-R053 An invoice total with VAT MUST equal the invoice total without VAT plus the VAT total amount and the rounding of invoice total 

### ISSUE THREAD

**Issue by ManjeetYadav** [difi/vefa-validator-conf#112]
Hi,

Invoice with following details fails with rule BII2-T10-R053 because of rounding of TaxExclusiveAmount.

Error on validator:
BII2-T10-R053 An invoice total with VAT MUST equal the invoice total without VAT plus the VAT total amount and the rounding of invoice total
\ Invoice-2:Invoice[1] \ cac:LegalMonetaryTotal[1]
Test: ((cbc:PayableRoundingAmount) and ((xs:decimal(cbc:TaxInclusiveAmount)) = (round((xs:decimal(cbc:TaxExclusiveAmount) + (xs:decimal(sum(/ubl:Invoice/cac:TaxTotal/cbc:TaxAmount))) + xs:decimal(cbc:PayableRoundingAmount)) *10 * 10) div 100))) or (not(cbc:PayableRoundingAmount) and ((xs:decimal(cbc:TaxInclusiveAmount)) = round((xs:decimal(cbc:TaxExclusiveAmount) + (xs:decimal(sum(/ubl:Invoice/cac:TaxTotal/cbc:TaxAmount)))) * 10 * 10) div 100))

Here is part of invoice:
<cac:TaxTotal>
		<cbc:TaxAmount currencyID="NOK">4287.50</cbc:TaxAmount>
		<cac:TaxSubtotal>
			<cbc:TaxableAmount currencyID="NOK">0.50</cbc:TaxableAmount>
			<cbc:TaxAmount currencyID="NOK">0.00</cbc:TaxAmount>
			<cac:TaxCategory>
				<cbc:ID schemeID="UNCL5305" schemeAgencyID="6">Z</cbc:ID>
				<cbc:Percent>0.00</cbc:Percent>
				<cac:TaxScheme>
					<cbc:ID>VAT</cbc:ID>
				</cac:TaxScheme>
			</cac:TaxCategory>
		</cac:TaxSubtotal>
		<cac:TaxSubtotal>
			<cbc:TaxableAmount currencyID="NOK">17150.00</cbc:TaxableAmount>
			<cbc:TaxAmount currencyID="NOK">4287.50</cbc:TaxAmount>
			<cac:TaxCategory>
				<cbc:ID schemeID="UNCL5305" schemeAgencyID="6">S</cbc:ID>
				<cbc:Percent>25.00</cbc:Percent>
				<cac:TaxScheme>
					<cbc:ID>VAT</cbc:ID>
				</cac:TaxScheme>
			</cac:TaxCategory>
		</cac:TaxSubtotal>
	</cac:TaxTotal>
	<cac:LegalMonetaryTotal>
		<cbc:LineExtensionAmount currencyID="NOK">17150.50</cbc:LineExtensionAmount>
		<cbc:TaxExclusiveAmount currencyID="NOK">17150.50</cbc:TaxExclusiveAmount>
		<cbc:TaxInclusiveAmount currencyID="NOK">21438.00</cbc:TaxInclusiveAmount>
		<cbc:PayableRoundingAmount currencyID="NOK">0.50</cbc:PayableRoundingAmount>
		<cbc:PayableAmount currencyID="NOK">21438.00</cbc:PayableAmount>
	</cac:LegalMonetaryTotal>

**Comment by SiwMeckelborg** [comment]
Please provide the entire file so we can use it for testing. File can be sent to siw.meckelborg@edisys.no, or you can send the link to the validation

**Comment by ManjeetYadav** [comment]
sent full file to your email address. Please check your inbox.

**Comment by SiwMeckelborg** [comment]
TaxInclusiveAmount and PayableAmount must also include the PayableRoundingAmount (as the error-text describes). Your LegalMonetaryAmount should be like this:
    	<cac:LegalMonetaryTotal>
		<cbc:LineExtensionAmount currencyID="NOK">17150.50</cbc:LineExtensionAmount>
		<cbc:TaxExclusiveAmount currencyID="NOK">17150.50</cbc:TaxExclusiveAmount>
		<cbc:TaxInclusiveAmount currencyID="NOK">21438.50</cbc:TaxInclusiveAmount>
		<cbc:PayableRoundingAmount currencyID="NOK">0.50</cbc:PayableRoundingAmount>
		<cbc:PayableAmount currencyID="NOK">21438.50</cbc:PayableAmount>
	</cac:LegalMonetaryTotal>

**Comment by ManjeetYadav** [comment]
Thanks. Closing it.
