### ISSUE TITLE
Difference in documentation and XSD - FinancialAccountType

### ISSUE THREAD

**Issue by SimonsUnikaNamn** [difi/vefa-validator-conf#122]
Reading the 8th page in the document 

https://github.com/difi/vefa-validator-conf/blob/master/STANDARD/EHFInvoice/2.0/guide/attachments-norwegian/Vedlegg%202%20Meldingstabellene/EHF%20faktura_meldingstabell.pdf

under cac:PayeeFinancialAccount there is a required element called cbc:ID. But looking at the actual code 

https://raw.githubusercontent.com/difi/vefa-validator-conf/updates-2016-05-23/STANDARD/common/xsd/UBL-2.1/xsd/common/UBL-CommonAggregateComponents-2.1.xsd

and searching for "FinancialAccountType" the element is described as

```
<xsd:element ref="cbc:ID" minOccurs="0" maxOccurs="1">
```

Where it is optional

**Comment by klakegg** [comment]
A lot of elements in UBL are optional where EHF says required as UBL is simply a syntax for holding data and does not define rules of EHF.
