### ISSUE TITLE
PEPPOL 3a, order only, wrong customizationID

### ISSUE THREAD

**Issue by SiwMeckelborg** [difi/vefa-validator-conf#124]
Customization ID for Order Only, PEPPOL 3a should be:
urn:www.cenbii.eu:transaction:biitrns001:ver2.0:extended:urn:www.peppol.eu:bis:peppol3a:ver2.0

In config file today there is ...peppol03a.... change to peppol3a.

**Comment by klakegg** [comment]
This is the information from PEPPOL:

![peppol03a](https://cloud.githubusercontent.com/assets/126939/13670191/bdb8c3de-e6c8-11e5-9ccc-bffc1bfc7cd9.png)

**Comment by klakegg** [comment]
Changes in [config.xml](https://github.com/difi/vefa-validator-conf/blob/updates-2015-10-01/STANDARD/config.xml) is out of scope as this file is not part of next release.
