### ISSUE TITLE
Facing Issue in IBAN validation 

### ISSUE THREAD

**Issue by rdineshrs** [difi/vefa-validator-conf#131]
`<cac:PayeeFinancialAccount>`
            `<cbc:ID schemeID="IBAN">DN</cbc:ID>`

 Tested in our webservice exposed for validator 2.0.1 

       Error : 
                  identifier : NOGOV-T10-R033
                  text : IBAN numbers MUST be Alpha-2 country code, followed by two check digits and then the BBAN. Only numbers and upper case literals A-Z is allowed.

 Same document Tested in  [https://vefa.difi.no/validator/]. 

        Warning :
                      NOGOV-T10-R033 IBAN number is not for a norwegain bank account

I have tested with new artifacts and I am getting the same error
may i know the reason ? have to upgrade anything  ?

**Comment by SiwMeckelborg** [comment]
If you are running your environment on EHF invoice 2.0.1, you need to upgrade, yes. Latest version is 2.0.5, and in the test-environment version 2.0.6 is found, and this version will be mandatory from 23. may 2016.

**Comment by klakegg** [comment]
The updated required was communicated months ago.
