### ISSUE TITLE
Value Added Tax (Norwegian MVA) 8% is not valid anymore?

### ISSUE THREAD

**Issue by juskoljo** [difi/vefa-validator-conf#135]
Hi,

Following documentation lists of valid VAT rates https://github.com/difi/vefa-validator-conf/blob/updates-2016-05-23/guides/ehf-invoice-and-creditnote-2.0/en/description/value-added-tax.adoc

As far as I know VAT rate 8% has been increased to 10% since Jan 1st 2016.

http://www.vatlive.com/european-news/norway-hikes-transport-hotel-vat-2016/
http://www.vatlive.com/vat-rates/international-vat-and-gst-rates/

BR,
Jussi

**Comment by SiwMeckelborg** [comment]
Thanks for informing us, table in chapter 6.6 is now updated
