### ISSUE TITLE
CompanyID validates ok without schemeID="NO:ORGNR" attribute

### ISSUE THREAD

**Issue by jangj** [difi/vefa-validator-conf#141]
Hi
In ehf invoice/creditnote, the file falis validation if the endpoint it lacks the schemeID="NO:ORGNR" attribute.
but this is ok:
 <cac:PartyLegalEntity>
 <cbc:CompanyID>810304642</cbc:CompanyID>

Shouldn't this fail?

The endpoint is recomended not mandatory.
If the endpint isn't there and the CompanyID hasn't got the schemeID="NO:ORGNR" attribute, the validator says the file is fine, but it fails when sending with oxalis-standalone or oxalis-outbound.

Error message:
2016-06-01 13:21:05,529 WARN [eu.peppol.xml.XML2DOMReader] Parsing aborted after 10 XML start elements 
2016-06-01 13:21:05,701 DEBUG [eu.peppol.document.PlainUBLHeaderParser] Creating DocumentParser for type : CreditNote 

Message failed : TransmissionRequest can not be built, missing [recipientId] metadata.

**Comment by klakegg** [comment]
Is this a proposal for a new rule, or is reporting a bug in an existing rule?

**Comment by jangj** [comment]
I guess it's both. 
The problem is that our customer claims their files are valid because they have tested them against the difi validator.
But our system cannot send them because they fail in oxalis-outbound.

**Comment by SiwMeckelborg** [comment]
Can you please provide an example-file?

**Comment by jangj** [comment]
[ComeplloTestAs-Creditnote.zip](https://github.com/difi/vefa-validator-conf/files/293443/ComeplloTestAs-Creditnote.zip)

Here is an example
Had to zip it

**Comment by SiwMeckelborg** [comment]
Looked at your example, and yes, there is actually no check that the attribute @schemeID exists for this element. I have reported this to PEPPOL as an issue: https://github.com/OpenPEPPOL/peppol-bis/issues/19
