### ISSUE TITLE
Conflicting handling of cbc:Note in XSD/Schematron and EHF Invoice and Creditnote 2.0.6 implementation guide

### ISSUE THREAD

**Issue by GjestadM** [difi/vefa-validator-conf#143]
We have a case where XSD + Schematron and EHF Invoice and Creditnote 2.0.6 implementation guide does not give us the same answer.
According to the XSD the field cbc:Note is a repeatable field:

Schematron allows several instances of this field as well.

In the "EHF Invoice structure.pdf" document it is stated that <cbc:Note> can have a maximum of 1 instances. 

I guess the "EHF Invoice structure.pdf" document or XSD/Schematron should be corrected so it gives the same result?

**Comment by SiwMeckelborg** [comment]
Hi,

there are several elements that have different cardinality between the ubl schematron and EHF. EHF is a subset of UBL, and hence not all elements/attributes in UBL are used in EHF, and also restrictions on cardinality has been added. The validation principles is that we validate that all elements that are sent are part of UBL, and that they are according to UBL. So an instance document can have elements that is part of UBL but not part of EHF, but the sender cannot expect the receiver to interpret these elements unless a bilateral agreement has been made.
