### ISSUE TITLE
Questions, Updated node tree?

### ISSUE THREAD

**Issue by stoivo** [difi/vefa-validator-conf#144]
I wonder if there is a node tree in the [new documentation](https://vefa.difi.no/ehf/guide/invoice-and-creditnote/2.0/en/validation/validation-service.html) like it existed in the old [pdf](https://github.com/difi/vefa-validator-conf/blob/8a35acc535d8601619143179361c68fe50b39268/STANDARD/EHFInvoice/2.0/guide/Implementation%20Guide%20EHF%20Invoicing%20Process%20v2.0.pdf) from page 40 to 72?

**Comment by SiwMeckelborg** [comment]
This one?
https://vefa.difi.no/ehf/gefeg/invoice/2.0/sp1.htm

**Comment by stoivo** [comment]
Exactly

Thanks @SiwMeckelborg
