### ISSUE TITLE
Publisher date or Utskriftsdato 

### ISSUE THREAD

**Issue by stoivo** [difi/vefa-validator-conf#148]
Hello

I have looked into https://vefa.difi.no/ehf/gefeg/invoice/2.0/st1.htm but I cant find anything about Publisher date or Utskriftsdato.

Does it exist in EHF?

**Comment by stoivo** [comment]
Ping

**Comment by SiwMeckelborg** [comment]
There is no specific element for Publisher date in EHF, why is this needed in addition to Issue date?

**Comment by stoivo** [comment]
NORSK RIKSKRINGKASTING AS has Publisher date(Utskriftsdato).
![207121](https://cloud.githubusercontent.com/assets/3492040/17543951/7a08af58-5ed4-11e6-8a20-33b4669bb384.jpg)
Publisher date is the date the invoice was created, and issue date is when it should be bookeeped. 

Another example is house rents. Some companies create house rests for 6 months at once. In this case that publisher date would be the date when that batch was created, and issue date the beginning of each period.

**Comment by SiwMeckelborg** [comment]
To my knowledge, publisher date is not a legal requirement in an invoice? And I cannot quite see what this information is used for? As you say, the issue date is the date of bookkeeping.  There is today no element for publisher date in EHF, and any new element requires a new version, not a revision.  There is an ongoing European project (TC434) to create a European Norm for invoices, and publisher date is not part of that model (at this point).  If the publisher wants to state the published date, this can also be done using some of the unstructured elements in EHF (cbc:Note as an example)

**Comment by stoivo** [comment]
Thank for help.
