### ISSUE TITLE
Financial invoices

### ISSUE THREAD

**Issue by tyskjohan** [difi/vefa-validator-conf#150]
I think it would be desirable to flag financial invoices (not based on an order) and services invoices (no delivery location) so that the following validation warnings can be skipped for e.g. interest invoices:
NONAT-T10-R003 - interest accrued does not have a delivery date
NONAT-T10-R004 - interest accrued does not have a delivery location
NOGOV-T10-R004 - interest accrued is not related to an order
NOGOV-T10-R002 - interest accrued is not an "item"

**Comment by SiwMeckelborg** [comment]
Can you please provide more details on this issue, as a lot of financial invoices (leasing, loans etc) can have delivery date/location and sellers ID. So this change request needs more details to be considered for a future new version of EHF Invoice.

**Comment by tyskjohan** [comment]
One example is, as I indicated, an interest invoice related to late payment of one or more other invoices - or a commercial "line-of-credit" loan (i.e. a loan that is not paid out in lump).

**Comment by tyskjohan** [comment]
Another example: every month, the Norwegian health regions invoice treatment of residents of other health regions. These invoices are not related to a sales order, nor can they be linked to a specific delivery date or location.

**Comment by klakegg** [comment]
Invoices in question are not easily distinguished from other invoices, so removing proposed warnings will lower quality of invoices in general.
