### ISSUE TITLE
BII2-T10-R034 as ERROR is returned on negative invoice lines

### ISSUE THREAD

**Issue by klakegg** [difi/vefa-validator-conf#151]

**Comment by klakegg** [comment]
This is reverted due to feedback during review process.

Negative invoice should use allowance for allowances and negativ amount of positive priceamount.

Test is not removed to make sure errors are triggered correct.

**Comment by toverlier** [comment]
The frase "negativ amount of positive priceamount" is somewhat confusing. It means "negative quantity of positive price amount", right?
