### ISSUE TITLE
Error in validation rule NONAT-T10-R026

### ISSUE THREAD

**Issue by SiwMeckelborg** [difi/vefa-validator-conf#157]
There is an error in the validation rule for NONAT-T10-R026. When summing up the allowances, the allowance/charge amount is not cast to decimal before rounding, resulting in wrong rounding in some special cases.

Line 2 raises an error when it should not, line 1 does not raise error.

Example file is added, renamed to txt format
[Avrunding_allowance_test.txt](https://github.com/difi/vefa-validator-conf/files/456609/Avrunding_allowance_test.txt)

**Comment by klakegg** [comment]
Invoice line 14 in test T10-avrunding-2.xml seems to be incorrect.

My math: 61.5000 * -174.65 = -10 740.975 ≈ **-10 740.97** (-0.97 is higher than 0.975)
The expected result in the test is **-10 740.98**

https://en.wikipedia.org/wiki/Rounding#Round_half_up

**Comment by klakegg** [comment]
8951ccd
