### ISSUE TITLE
Modulus 11 check on organization number

### ISSUE THREAD

**Issue by joerahol** [difi/vefa-validator-conf#169]
Modulus 11

Hi

We have several invoices each week with invalid organization number in the PartyLegalEntity element for both supplier and customer.
In both cases, it leads to manual handling as to figure out whom of my customers the invoice is to and manual handling for my customers to match the invoice to the ERP supplier table.
It would be good if the validator would give an Error if not matched with modulus 11 check.

Regards
Per Martin
DFØ

**Comment by klakegg** [comment]
This is solved by updating existing validation of organization numbers.

Rules for invoices are updated and may be tested in our validator for pre-release purposes. Please verify.
