### ISSUE TITLE
Too long text in UBL-10-BiiRules.xsl

### ISSUE THREAD

**Issue by gunnarvo** [difi/vefa-validator-conf#17]
Hi!
I have some problems when compiling UBL-T10-BiiRules.xsl.

I include the XSL files in a local .NET project for performing validation of EHF2.0 documents.
But from .NET framework 4.5/Visual Studio 2012 I get the following error: "XSLT compile error. The stylesheet is too complex".

The error is linked to the fact that the test for correct MIME Values in line 1134 is over 31.000 characters long. If I reduce this string down to some place around 28.000 characters, the error disappears.

Has anyone else experienced any problems like this? What did you do to overcome this?
Alternatively - Could this have been rewritten so that it does not conflicts with .NET?
(The problem is the same with the CreditNote counterpart: UBL-T14-BiiRules.xsl)

The problem was not present in the xsl files from "Pre May 2014" (Old EHF 2.0)

Gunnar Vøyenli
Xledger

**Comment by klakegg** [comment]
BII rules are handed over from PEPPOL BIS. We will not start to change PEPPOL BIS files in EHF. There are also no other registered issues regarding long lines.
