### ISSUE TITLE
BIS Catalogue validation returns "Unknown Document type" error.

### ISSUE THREAD

**Issue by kristdeveugele** [difi/vefa-validator-conf#178]
https://vefa.difi.no/validator/v/9851e42d-a6dd-4ce4-9c9f-ab66ed35ac1b

[Catalogue Use case 1.zip](https://github.com/difi/vefa-validator-conf/files/506131/Catalogue.Use.case.1.zip)

**Comment by klakegg** [comment]
Not a bug in EHF.

**Comment by kristdeveugele** [comment]
I agree that it is not a bug in EHF, but it is imho a bug in the validator.  The validator homepage mentions that PEPPOL BIS 01A Catalogue Only 2.0 is a supported standard, but it does not work.

**Comment by klakegg** [comment]
It is not a bug in the validator, and still not relevant in this repo.
