### ISSUE TITLE
Schematrons for review

### ISSUE THREAD

**Issue by monze** [difi/vefa-validator-conf#185]
Hello

We are using your xslt Schematron stylesheets to validate all EHF documents that we send and receive through the Peppol Infrastructure. The next release of EHF schematron is dated to 2016-11-15. The only place I can find these resources is here: https://github.com/difi/vefa-validator-conf/tree/upcoming/rules. This is also the places we are re-directed to from https://vefa.difi.no/ehf/announcement/2016-10-17-new-releases-for-review/ when we click on any of the document types.

I have noticed, that the source for the schematron exist in the sch directory, and the compiled version exist in xsl directory.

My question is simply, if we should use the provided compile xslt stylesheet, or if we are expected to compile our own schematrons based on the sch files?

- If we are to compile our version, exactly how should we do that? Can't find the instruction on howto compile, to insure that we create the correct Schematron. Further, if we are to compile our own version, the xsl folder should be removed so no-one is in doubt.

- If we are to use the compiled version in the xsl directory, then I must inform you that those resources are not up to date. They where committed to GitHub the 5. of October, but the source sch files has been changed many times since that.

Due to this we can't make a review of the schematrons.

Jacob Mogensen
mySupply Aps
Denmark

**Comment by klakegg** [comment]
Each XSLT or Schematron file has a filename where the basename describes the type of rules within the file. Validation must be according to the validation pyramid.

**Comment by monze** [comment]
klakegg, please - a least to the time take to read the issue, before closing it.

It has nothing to due with the filename, nor the validation pyramid.

The issue is that Difi hasn't released the compile xsl Schematron for the upcomming 2016-11-15 release. Closing the issue does NOT make the problem go away...

Jacob Mogensen
mySupply ApS
Denmark

**Comment by klakegg** [comment]
EHF uses ISO Schematron, exactly like PEPPOL BIS. Generating XSLT or any other artifact may be done according to the ISO standard.
