### ISSUE TITLE
MVA-number. NOxxxxxxxxxMVA

### ISSUE THREAD

**Issue by BaoNguyenD** [difi/vefa-validator-conf#40]
Hi. 

With EHF 2.0.3 validation, there is strict with the format for VAT number. It should be xxxxxxxxxMVA but both the example in the dataformat http://vefa.difi.no/formatvisning/faktura/2.0/ and the implementation guide section 6.15 told something else. It is easy to misunderstand so please fix the wording in the guide and the example to reduce the problem about how the VAT number should be.

BR
Bao

6.15 LEVERANDØRENS MVA NUMMER 
Leverandørens MVA nummer angis i elementet Invoice/cac:AccountingSupplierParty/cac:Party/cac:PartyTaxScheme/cbc:CompanyID og 
er opprinnelig et valgfritt felt, men i følge EU COUNCIL DIRECTIVE 2001/115/ må elementet sendes dersom faktura eller kreditnota har en MVA total. Det betyr i praksis at feltet nesten alltid må sendes. For virksomheter registrert i Norge er det organisasjonsnr. etterfulgt av bokstavene MVA (123456789MVA) som skal sendes. Det anbefales bruk av NO som prefiks ved fakturering til utlandet. 
Eksempel: 
<cac:PartyTaxScheme> 
<cbc:CompanyID schemeID="NO:VAT">NO123456789MVA</cbc:CompanyID> 
<cac:TaxScheme> 
<cbc:ID>VAT</cbc:ID> 
</cac:TaxScheme> 
</cac:PartyTaxScheme>

**Comment by SiwMeckelborg** [comment]
Thanks for informing us, the example will be fixed in the next revision.

**Comment by digitalnomade** [comment]
When will 2.0.4 be implemented

**Comment by klakegg** [comment]
That depends on announcements. Earliest possible date for production is April 1st.
