### ISSUE TITLE
Error in validation for Credit note EHF 2.0.3. Rule [NONAT-T14-R024]-

### ISSUE THREAD

**Issue by BaoNguyenD** [difi/vefa-validator-conf#41]
Hi.
It seems so that there is a error in Credit note validation for line amount when there is AllowanceCharge. The valitaion do not count AllowanceChage. The creditnote line below should not raise any error but it got the following   

Error: [NONAT-T14-R024]-Credit note line amount MUST be equal to the price amount multiplied by the quantity, plus charges minus allowances at the line level. 

Examle
<cbc:CreditedQuantity unitCodeListID="UNECERec20" unitCode="EA">1.00</cbc:CreditedQuantity>
      <cbc:LineExtensionAmount currencyID="NOK">-500.00</cbc:LineExtensionAmount>
      <cac:AllowanceCharge xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2">
        <cbc:ChargeIndicator>false</cbc:ChargeIndicator>
        <cbc:Amount currencyID="NOK">1000</cbc:Amount>
      </cac:AllowanceCharge>
      <cac:Item>
        <cbc:Name>Returgebyr</cbc:Name>
        <cac:SellersItemIdentification>
          <cbc:ID>RETURGEBYR</cbc:ID>
        </cac:SellersItemIdentification>
        <cac:ClassifiedTaxCategory>
          <cbc:ID schemeID="UNCL5305">S</cbc:ID>
          <cbc:Percent>25.00</cbc:Percent>
          <cac:TaxScheme>
            <cbc:ID>VAT</cbc:ID>
          </cac:TaxScheme>
        </cac:ClassifiedTaxCategory>
      </cac:Item>
      <cac:Price>
        <cbc:PriceAmount currencyID="NOK">500.00</cbc:PriceAmount> 

BR
Bao

**Comment by SiwMeckelborg** [comment]
Hi Bao, could you please send me a copy of the file that gives you this error, so I can test it? email: siw.meckelborg@edisys.no

**Comment by SiwMeckelborg** [comment]
Hi Bao, you are correct, there is an error in this validation rule. The rule does calculate the allowance, but there is an issue when the allowance is larger than the sum of quantity*price. Same error also occurs in the corresponding rule on invoices. Will be fixed in next revision.

**Comment by juskoljo** [comment]
This fix seems to break CreditNoteLine amounts validation? It seems to occur only if LineExtensionAmount is negative. No validation errors occur with below values:

CreditedQuantity = 1234567.00
LineExtensionAmount = -800.00
PriceAmount = 100.00

The same result regardless if there is line AllowanceCharge's or not.

**Comment by SiwMeckelborg** [comment]
Issue has been fixed
