### ISSUE TITLE
Add possibility to use Office2013 document-types as attachments . Issue reported on LinkedIn

### ISSUE THREAD

**Issue by SiwMeckelborg** [difi/vefa-validator-conf#42]
Text from LinkedIn: "De "nye" MIME-typene for XML-baserte Microsoft Office-dokument ikke er støttet. Dvs at dette er støttet: application/msword mens dette (korrekte) ikke er støttet: application/vnd.openxmlformats-officedocument.wordprocessingml.document"

**Comment by tyskjohan** [comment]
Thanks for picking this up!

**Comment by SiwMeckelborg** [comment]
In EHF Invoice there is a recommondation to use only a few of the allowed Mime types, as sending other types of attachments means the receiver must have support for several versions of different software. Result is that we will generate a warning if attachment is not in the recommended list.

**Comment by Kanozujo** [comment]
How long will the 10 year old-new formats stay in the not-recommended list? Isn't it about time to update the list of recommended types of attachment to include .docx, and not .doc. (safer for macro's too)

**Comment by klakegg** [comment]
Please see answer from Siw above.
