### ISSUE TITLE
Specification of business sector for the invoice

### ISSUE THREAD

**Issue by SiwMeckelborg** [difi/vefa-validator-conf#44]
There has been a request to add functionality for how to specify which sector the invoice is covering, example utility sector. Suggestion is to add a document reference with LineOfBusiness=6 (Codelist from E2B,  1=Kort 2=Reise 3=Telecom 4=Transport 5=Frakt 6=Energi 9=Generelle varer). 

Example:
<cac:AdditionalDocumentReference>
  <cbc:ID>6</cbc:ID>
  <cbc:DocumentType>LineOfBusiness</cbc:DocumentType> 
</cac:AdditionalDocumentReference>

**Comment by pjbridge** [comment]
We currently use code 82, "Metered services Invoice" (code list UNCL1001 http://www.unece.org/trade/untdid/d98a/uncl/uncl1001.htm) to identify the invoice as an utility invoice. The code is placed under ContractDocumentReference - DocumentTypeCode. 
Could this be an alternative to the above suggestion? 
Or perhaps lift the restriction on InvoiceTypeCode , so the code 82 could be placed there.

**Comment by SiwMeckelborg** [comment]
This change request will not be implemented in EHF Invoice
