### ISSUE TITLE
Cardinality of PartyLegalEntity for CustomerParty

### ISSUE THREAD

**Issue by BaoNguyenD** [difi/vefa-validator-conf#53]
hi, Cardinality for PartyLegalEntity for AcountingCustomerParty need to be change from 0..1 to 1..1 in the online datamodel
http://vefa.difi.no/formatvisning/faktura/2.0/guideline/gl1.htm?http://vefa.difi.no/formatvisning/faktura/2.0/guideline/gl5.htm

**Comment by SiwMeckelborg** [comment]
Legal Entity for AccountingCustomerParty is not mandatory, but dependant. If the invoice is for private consumers, it should not be filled. Please also see chapter 6.13 in the implementation guide for further details.
