### ISSUE TITLE
Blank InvoiceLine/ID allowed?

### ISSUE THREAD

**Issue by senikk** [difi/vefa-validator-conf#54]
One of our customers has received files where cbc:ID is blank and still it goes trough the EHF validator without any other warnings then the common not having blank elements. In the documentation it says that InvoiceLine/ID is mandatory. Should the validator given an error or is it allowed? 

    <cac:InvoiceLine>
        <cbc:ID></cbc:ID>

**Comment by SiwMeckelborg** [comment]
According to the guide, empty elements are not allowed in EHF (see chapter 3.3). This will however only generate a warning, not an error in the validation as it is today. I will add this issue to the backlog, and discuss if a stricter validation should be applied for this element.

**Comment by SiwMeckelborg** [comment]
In the guide for EHF (chapter 3.3) it is clearly stated that empty elements are not allowed. Even so, we see a lot of invoices/credit notes with empty elements. There is a need to validate this, but we have been given signals that this will be a major change for the ERP systems to change, so this validation will not be a part of revision 2.0.4, but will be added in the first revision/version after that. (First possible date will then be 1.July 2015)
