### ISSUE TITLE
OrderResponse for International actors CustomizationID incorrect

### ISSUE THREAD

**Issue by Seven25** [difi/vefa-validator-conf#70]
When trying to validate Order Responses using the following 

ProfileID = urn:www.cenbii.eu:profile:bii28:ver2.0
CusotmizationID = urn:www.cenbii.eu:transaction:biitrns076:ver2.0:extended:urn:www.peppol.eu:bis:peppol28a:ver1.0

The combination is not recognized this is due to the following in the config file

<validate
id="urn:www.cenbii.eu:profile:bii28:ver2.0 urn:www.cenbii.eu:transaction:biitrns076:ver2.0:extended:urn:www.peppol.eu:bis:peppol28a:ver1.0"
version="1.0">

There is a ' ' where there should be a '#'

**Comment by klakegg** [comment]
We will fix this in the next revision.
