### ISSUE TITLE
Prevent PEPPOL BIS invoices to be sent between Norwegian parties

### ISSUE THREAD

**Issue by joerahol** [difi/vefa-validator-conf#71]
A PEPPOL BIS invoice is not a legal Norwegian invoice between Norwegian buyer and supplier. There is a need to prevent such invoice to be sent.

**Comment by SiwMeckelborg** [comment]
Isn't this covered by the fact that there must be a norwegian organisation number? Rule ID NOGOV-T10-R031, An organisational number for seller, buyer and payee MUST be nine numbers.

**Comment by SiwMeckelborg** [comment]
After a brief discussion with joerahol, I realized I misunderstood this issue. Change request will be discussed, and any remarks/decisions will be reported here.

**Comment by SiwMeckelborg** [comment]
A validation to prevent this, must take into account the use of PayeeParty and taxRepresentative Party as well as seller and buyer.
