### ISSUE TITLE
Missing PartyTaxScheme triggers [BII2-T10-R044] for orgs without MVA 

### ISSUE THREAD

**Issue by Lamisi** [difi/vefa-validator-conf#75]
When PartyTaxScheme is omitted, this rule is broken [BII2-T10-R044]-A seller VAT identifier MUST be provided if the invoice has a VAT total amount. I was adviced to omit PartyTaxScheme because the org.number is exempt from MVA, hence MVA should not be apart of the organisation number.
How do you bypass this?

**Comment by klakegg** [comment]
Is this related to your question in #36?

**Comment by SiwMeckelborg** [comment]
PartyTaxScheme should only be omitted if the the supplier is not registered in the VAT-registry in Norway (MVA-registeret). The rule BII2-T10-R044 is not run when you validate an EHF invoice in the validator from Difi, a separate Norwegian rule NOGOV-T10-R014 is run instead. The omitting of the BII-rule can be seen in the config-file of the Difi-validator (https://github.com/difi/vefa-validator-conf/blob/master/STANDARD/config.xml, where it is filtered out)

**Comment by Lamisi** [comment]
Thank you!

**Comment by SiwMeckelborg** [comment]
I assume you have received the answer you needed, and hence I close this issue.

**Comment by phax** [comment]
The current exclusion list can now be found in https://github.com/anskaffelser/ehf-postaward-g2/blob/master/tools/script/schematron.sh
