### ISSUE TITLE
EHF 2.0.4 CreditNote NONAT-T14-R024 - calculation should not consider abs values

### ISSUE THREAD

**Issue by vtapadia** [difi/vefa-validator-conf#78]
Regarding the rule added/corrected in the new version UBL-T14-Nonat.xsl.
```xml
<axsl:when test="not(cbc:CreditedQuantity) or 
            not(cac:Price/cbc:PriceAmount) or 
            number(cbc:LineExtensionAmount) &gt; 0 
            or (cbc:CreditedQuantity) &gt; 0 
            or 
            (not(cac:Price/cbc:BaseQuantity)  and abs(number(cbc:LineExtensionAmount)) =
            round(((round((10 * 10) * xs:decimal(cac:Price/cbc:PriceAmount) * abs(xs:decimal(cbc:CreditedQuantity))) div 100) +
            ((round(sum(cac:AllowanceCharge[child::cbc:ChargeIndicator='true']/cbc:Amount) *10 * 10) div 100 ) - 
            (round(sum(cac:AllowanceCharge[child::cbc:ChargeIndicator='false']/cbc:Amount) *10 * 10) div 100 )) * -1 ) * 10 * 10) div 100) or
            ((cac:Price/cbc:BaseQuantity) and 
            abs(number(cbc:LineExtensionAmount)) = round(((round((10 * 10) * (xs:decimal(cac:Price/cbc:PriceAmount) div xs:decimal(cac:Price/cbc:BaseQuantity)) * abs(xs:decimal(cbc:CreditedQuantity))) div 100) +
            ((round(sum(cac:AllowanceCharge[child::cbc:ChargeIndicator='true']/cbc:Amount) * 10 * 10) div 100 ) -
            (round(sum(cac:AllowanceCharge[child::cbc:ChargeIndicator='false']/cbc:Amount) *10 * 10) div 100)) * -1) *10 *10) div 100)"/>
```

Here the calculation is when both LineExtAmount and CreditQuantity is -ve.

We have received a Credit Line with below details..
```xml
<cac:CreditNoteLine>
    <cbc:ID>2</cbc:ID>
    <cbc:CreditedQuantity unitCode="ZZ" unitCodeListID="UNECERec20">-10.00</cbc:CreditedQuantity>
    <cbc:LineExtensionAmount currencyID="NOK">-289.59</cbc:LineExtensionAmount>
    <cac:TaxTotal>
      <cbc:TaxAmount currencyID="NOK">-72.40</cbc:TaxAmount>
    </cac:TaxTotal>
    <cac:AllowanceCharge>
      <cbc:ChargeIndicator>false</cbc:ChargeIndicator>
      <cbc:AllowanceChargeReason>Line discount</cbc:AllowanceChargeReason>
      <cbc:MultiplierFactorNumeric>0.30</cbc:MultiplierFactorNumeric>
      <cbc:Amount currencyID="NOK">124.11</cbc:Amount>
      <cbc:BaseAmount currencyID="NOK">413.70</cbc:BaseAmount>
    </cac:AllowanceCharge>
    <cac:Item>
      <cbc:Name>xxxxxx</cbc:Name>
      <cac:SellersItemIdentification>
        <cbc:ID>111111111</cbc:ID>
      </cac:SellersItemIdentification>
      <cac:StandardItemIdentification>
        <cbc:ID schemeAgencyID="9" schemeID="GTIN">111111111111</cbc:ID>
      </cac:StandardItemIdentification>
      <cac:ClassifiedTaxCategory>
        <cbc:ID schemeID="UNCL5305">S</cbc:ID>
        <cbc:Percent>25.00</cbc:Percent>
        <cac:TaxScheme>
          <cbc:ID schemeID="UN/ECE 5153">VAT</cbc:ID>
          <cbc:Name>Value Added Tax</cbc:Name>
        </cac:TaxScheme>
      </cac:ClassifiedTaxCategory>
    </cac:Item>
    <cac:Price>
      <cbc:PriceAmount currencyID="NOK">41.37</cbc:PriceAmount>
    </cac:Price>
  </cac:CreditNoteLine>
```

This fails in the above validation. However, we feel that the file is correct.
As per the rule, we are taking the absolute values of LineExtAmount and CreditQuantity...however, we are adjusting the calculation for AllowanceCharge by multiplying it by -1. This leads to the calculated value being not equal.

We think, this calculation should not do the abs conversion. Kindly advice if our understanding is incorrect.

**Comment by SiwMeckelborg** [comment]
The calculation in your sample is not correct. LineExtensionAmount should be = (price*quantity) MINUS allowance and plus charges. In your example you have calculated (price*quantity) PLUS allowances.

The following line is valid, with LineExtension = -537.81   ( (41,37 * -10) - 124,11)

	<cac:CreditNoteLine>
		<cbc:ID>2</cbc:ID>
		<cbc:CreditedQuantity unitCode="ZZ" unitCodeListID="UNECERec20">-10.00</cbc:CreditedQuantity>
		<cbc:LineExtensionAmount currencyID="NOK">-537.81</cbc:LineExtensionAmount>
			<cac:AllowanceCharge>
			<cbc:ChargeIndicator>false</cbc:ChargeIndicator>
			<cbc:AllowanceChargeReason>Line discount</cbc:AllowanceChargeReason>
			<cbc:MultiplierFactorNumeric>0.30</cbc:MultiplierFactorNumeric>
			<cbc:Amount currencyID="NOK">124.11</cbc:Amount>
			<cbc:BaseAmount currencyID="NOK">413.70</cbc:BaseAmount>
		</cac:AllowanceCharge>
		<cac:Item>
			<cbc:Name>xxxxxx</cbc:Name>
			<cac:SellersItemIdentification>
				<cbc:ID>111111111</cbc:ID>
			</cac:SellersItemIdentification>
			<cac:StandardItemIdentification>
				<cbc:ID schemeAgencyID="9" schemeID="GTIN">111111111111</cbc:ID>
			</cac:StandardItemIdentification>
			<cac:ClassifiedTaxCategory>
				<cbc:ID schemeID="UNCL5305">S</cbc:ID>
				<cbc:Percent>25.00</cbc:Percent>
				<cac:TaxScheme>
					<cbc:ID schemeID="UN/ECE 5153">VAT</cbc:ID>
					<cbc:Name>Value Added Tax</cbc:Name>
				</cac:TaxScheme>
			</cac:ClassifiedTaxCategory>
		</cac:Item>
		<cac:Price>
			<cbc:PriceAmount currencyID="NOK">41.37</cbc:PriceAmount>
		</cac:Price>
	</cac:CreditNoteLine>

**Comment by vtapadia** [comment]
Agreed, but we are multiplying the allowance change value with -1.

That negates the calculation.

((round(sum(cac:AllowanceCharge[child::cbc:ChargeIndicator='true']/cbc:Amount) *10 * 10) div 100 ) - 
            (round(sum(cac:AllowanceCharge[child::cbc:ChargeIndicator='false']/cbc:Amount) *10 * 10) div 100 )) * -1 )

**Comment by vtapadia** [comment]
Also, I still think the rule mentioned in #77 is a different issue.
There are in total - 3 rules for NONAT-T14-R024 error.

And I think, the third one is incorrect.

**Comment by SiwMeckelborg** [comment]
I'm not sure I fully understand the issue. But the line you have pasted in at the top, generates an error for the first of the three rules, not the third one. The third will fire if you have negative LineExtension and positive CreditedQuantity. 

In the first rule, we mulityply by -1, yes, but we also check that against the absolute value:
![image](https://cloud.githubusercontent.com/assets/9652905/7112663/29eb9e94-e1cc-11e4-985f-8b1bc3311458.png)

The rule states:
Credit note line amount MUST be equal to the price amount multiplied by the quantity, plus charges minus allowances at the line level.

So, price * quantity MINUS allowance PLUS charges

In your example you have a LineExtensionAmount = price*quantity PLUS allowance, and that is not correct.

**Comment by SiwMeckelborg** [comment]
for the third of this rule, I have added my comments in issue #77

**Comment by vtapadia** [comment]
When we multiply the allowance change by -1, the charge becomes addition than subtraction.

Let me try to explain based on my data..
(abs(-10) * 41.37) + ( (0-124.11) * -1) = 537.81

Now, if you just remove the abs... the result becomes.
(-10 * 41.37) + ( (0-124.11) * -1) = -289.59

My understanding says that the multiplication to -1 for the allowance charge is correct. Because that takes care of the scenario where the LineExtAmount is -ve. However, the final calculation should not ignore the -ve value for the LineExtAmount and Quantity.. because that makes the calculation incorrect.

If the values (LineExtAmount and PriceQuantity) had been positive, the rule is as follows
```xml
(number(cbc:LineExtensionAmount)) = 
            round(((round((10 * 10) * xs:decimal(cac:Price/cbc:PriceAmount) * xs:decimal(cbc:CreditedQuantity)) div 100) + 
            (round(sum(cac:AllowanceCharge[child::cbc:ChargeIndicator='true']/cbc:Amount) *10 * 10) div 100 ) - 
            (round(sum(cac:AllowanceCharge[child::cbc:ChargeIndicator='false']/cbc:Amount) *10 * 10) div 100 ) ) * 10 * 10) div 100)
```

Which is 
LineExtAmount = Price * Quantity + (AllowanceChange (ChargeIndicator=true) - AllowanceChange (ChargeIndicator=false))

With negative values for LineExtAmount, we are also doing the same thing... and for that we are multiplying allowance charge by -1 which is also valid. Say, for subtracting from a -ve value we need to add a positive value and the -1 multiplication does that... but since we have taken the absolute value, the calculation does not add up.

**Comment by SiwMeckelborg** [comment]
This issue has previously been discussed as well, and conclusion was then that there should be the same calculation even if quanitity is negative. So in your case, you must not multiply the amount with -1, but send it as a charge instead of an allowance (chargeindicator = true)
