### ISSUE TITLE
Revert change on schemeID for ClassifiedTaxCategory, issue #45

### ISSUE THREAD

**Issue by SiwMeckelborg** [difi/vefa-validator-conf#79]
An issue has been raised on LinkedIn, connected to issue #45 
https://www.linkedin.com/groups/Mostridende-opplysninger-om-bakoverkompatibilitet-av-4647203.S.5993682060919787521?trk=groups_most_recent-0-b-ttl&goback=%2Egmr_4647203

Decision has been made that this change needs to be reverted in a hotfix, where the new rule for Invoice and Credit note will be removed. We apologize for this mistake.

**Comment by klakegg** [comment]
Related to #45.
