### ISSUE TITLE
Performance issues with large Invoices in terms of InvoiceLines(1000-2000+)

### ISSUE THREAD

**Issue by lifeanxiety** [difi/vefa-validator-conf#8]
When validating real world invoices with more than 1000 lines we have discovered severe performances issues. 
One such document could take more than 20 minutes using latest VEFAvalidationConf and App 

This is the configuration we are experiencing the performance issues

	<validate id="urn:www.cenbii.eu:profile:bii04:ver1.0#urn:www.cenbii.eu:transaction:biicoretrdm010:ver1.0:#urn:www.peppol.eu:bis:peppol4a:ver1.0#urn:www.difi.no:ehf:faktura:ver1" 
		version="1.6"
		render="true">
		...
	</validate>

We believe the performance issues are in this resources VEFAvalidatorConf\STANDARD\EHFInvoice\1.6\xsl\UBL-T10-Nogov.xsl and VEFAvalidatorConf\STANDARD\EHFInvoice\1.6\xsl\UBL-T10-Nonat.xsl

Could you take a look into this performance issue?
What is your opinion on this?

**Comment by raman-kant** [comment]
We are also facing same issue for EHF invoice  , it took 15 min to validate.

**Comment by SiwMeckelborg** [comment]
I'll add this as an action-point to see if there is some tuning that can be done in the schematrons.

**Comment by SiwMeckelborg** [comment]
If you have the possibility to send me a test-file, please send to siw.meckelborg@edisys.no

**Comment by pr0nin** [comment]
We are also having issues with this. According to the consultant that tested it, the http://vefa.difi.no/validator/ also times out trying to validate these files.

I'll send you an example file @SiwMeckelborg

**Comment by pr0nin** [comment]
Were you able to validate the example file I sent you @SiwMeckelborg and how much time did it take to validate it?

**Comment by klakegg** [comment]
This issue is solved by the new validator implementation.
