### ISSUE TITLE
Missing example files

### ISSUE THREAD

**Issue by klakegg** [difi/vefa-validator-conf#81]
The last revision of EHF invoice and creditnote lacks example files in the attachments.

Example files may also be found here ("BII05 T10 gyldig faktura.xml" and "BII05 T14 gyldig kreditnota.xml"):
https://github.com/difi/vefa-validator-conf/tree/master/STANDARD/EHFInvoice/2.0/test

**Comment by oskaremil** [comment]
Adding to this: 1.4 files are deleted so the validator-app tests fail. I was told to create an issue in the validator-conf project for it...
