### ISSUE TITLE
Update the validator definitions

### ISSUE THREAD

**Issue by mattiz** [difi/vefa-validator-conf#83]
The documentation is a little unclear regarding update of the validator. As far as I know, there is a new revision every month that will cover any changes made to the EHF format.

Is it enough to pull the latest version from the vefa-validator-conf repository to get the latest validator definitions? Or do I also have to pull and build vefa-validator-app?

**Comment by SiwMeckelborg** [comment]
Have you received answer to this one in LinkedIn or via support?

**Comment by mattiz** [comment]
No answer yet.

**Comment by klakegg** [comment]
This repository is updated with new versions when announced. Updated configuration doesn't trigger a need to rebuild the validator.
