### ISSUE TITLE
AccountingCustomerParty/Party/Contact/ID when no reference is given

### ISSUE THREAD

**Issue by klakegg** [difi/vefa-validator-conf#84]
When no reference is given by customer, the element AccountingCustomerParty/Party/Contact/ID must contain the value "NA".

This should be documented in the implementation guide.

**Comment by bebha** [comment]
Buer Benedicte would like to recall the message, "[vefa-validator-conf] AccountingCustomerParty/Party/Contact/ID when no reference is given (#84)".

**Comment by bebha** [comment]
Hei!
Hvilken kunde/virksomhet gjelder dette? Hvorfor får jeg denne mailen? Har en av våre kunder sendt noe til dere som har feilet?

Med vennlig hilsen

Benedicte Buer
Senior systemkonsulent
Tel: +47 997 98 280
benedicte.buer@norconsult.com

Norconsult Informasjonssystemer AS, Postboks 433, NO-2303 Hamar
Torggata 22, NO-2317 Hamar
Tel: +47 62 02 52 00 | Fax: +47 67 54 45 76
www.norconsult.no<http://www.norconsult.no/>

[9184237]<https://twitter.com/NoIS_no>  [9184235] <http://www.linkedin.com/company/norconsult-informasjonssystemer-as>
Visste du at NoIS er på Twitter og LinkedIn? Følg oss!

CONFIDENTIALITY AND DISCLAIMER NOTICE: This message is for the sole use of the intended recipients and may contain confidential information. If you are not an intended recipient, you are requested to notify the sender by reply e-mail and destroy all copies of the original message. Any unauthorized review, use, disclosure or distribution is prohibited. While the sender has taken reasonable precautions to minimize the risk of viruses, we cannot warrant the absence of, or accept liability for, any such viruses in this message or any attachment.

**Comment by thomasnakken** [comment]
Is this update also for the validator? Will invoices with blank  AccountingCustomerParty/Party/Contact/ID be marked with FATAL error and stopped?

**Comment by SiwMeckelborg** [comment]
No, this change is only in the implementation guide, to recommend the use of NA if this information is not relevant for the invoice. But, be aware of the change that will be implemented in the next revision in October, where ALL empty elements will result in a FATAL error and stopped. The implementation guides clearly states (chapter 3.3) that empty elements is not allowed, and from October this will also be added to the validation rules. See issue #72 

https://github.com/difi/vefa-validator-conf/issues/72
