### ISSUE TITLE
Add validation of "PEPPOL BIS 3A Order Only" orders to validator

### ISSUE THREAD

**Issue by cdruschk** [difi/vefa-validator-conf#85]
The validator doesn´t support validation of orders with customizationID and profileID as following: 
   <cbc:CustomizationID>urn:www.cenbii.eu:transaction:biitrns001:ver2.0:extended:urn:www.peppol.eu:bis:peppol03a:ver2.0</cbc:CustomizationID>
   <cbc:ProfileID>urn:www.cenbii.eu:profile:bii03:ver2.0</cbc:ProfileID>

When trying to validate such an order you get this error: 

"Error: No validation definition is found in configuration."

It´s understood that EHF makes use of the "PEPPOL BIS 28A Ordering" profile but the "PEPPOL BIS 3A Order Only" might be used in cross border scenarios. Also not all customers in Norway are able to process order responses and then the "PEPPOL BIS 3A Order Only" is an option, too. 

Please add support for it in the validator.

**Comment by SiwMeckelborg** [comment]
This issue will be up for discussion in our next governance meeting, but I would like to state that between Norwegian actors, only EHF profiles must be used, not PEPPOL BIS. So your reasoning that this can be used for norwegian actors not able to process order response is not a good argument.

**Comment by SiwMeckelborg** [comment]
Requires change in config.xml
