### ISSUE TITLE
NONAT-T10-R025 is raised incorrectly for terse/compact XML

### ISSUE THREAD

**Issue by tyskjohan** [difi/vefa-validator-conf#86]
I am getting NONAT-T10-R025 (An invoice SHOULD not contain empty elements) for XML that is not pretty-printed, i.e. where all the XML is on a single line with no line breaks. If I pretty-print the same XML in XMLSpy, the same error is not raised. I think the XPath must be modified to only flag elements that have empty text and also don't have any children.

I.e. change

    not(count(//*[not(text())]) > 0)

to

    not(count(//*[not(text()) and count(*) = 0]) > 0)

**Comment by tyskjohan** [comment]
Oops. Note that the markup parser "ate" my asterisks. One should be after the double slashes and one inside the brackets after count.

**Comment by tyskjohan** [comment]
Example file exposing the behaviour: https://gist.github.com/tyskjohan/afeb35b19e2b18593273

**Comment by tyskjohan** [comment]
Alternatively,

    not(count(//*[not(node())]) > 0)

might be a better and more terse solution.

**Comment by tyskjohan** [comment]
After thinking about this even more, I believe this rule both
 * better illustrates what's wrong with the existing rule
 * illustrates what it is we actually want to validate

    not(count(//*[not(normalize-space()) and count(*) = 0]) > 0)

**Comment by SiwMeckelborg** [comment]
Thanks for reporting this issue. Check has been changed to:
not(count(//*[not(node())]) &gt; 0) for both invoice and credit note

**Comment by tyskjohan** [comment]
Hi

I think this should be re-opened and fixed with count() and normalize-space() as proposed above. See the comments exchanged with Klakegg on LinkedIn.

Sent from a mobile device.
+47 975 675 39

**Comment by SiwMeckelborg** [comment]
Could you please add a link to the LinkedIn discussion? What forum has this been discussed in there?

**Comment by tyskjohan** [comment]
The discussion is amongst the comments here:

Nye revisjoner av EHF gjeldende fra 1. juli, varsel om nye revisjoner 1. oktober | LinkedIn

https://www.linkedin.com/grp/post/4647203-6003955169841201156

Sent from a mobile device.
+47 975 675 39

**Comment by tyskjohan** [comment]
I have updated the Gist at https://gist.github.com/tyskjohan/afeb35b19e2b18593273 with some examples that show the problems with
   not(count(//*[not(node())]) > 0)
and why it's better to use
   not(count(//*[not(normalize-space()) and count(*) = 0]) > 0)
(see lines 27 and 36 in the Gist)

**Comment by tyskjohan** [comment]
This problem seems to exist also on the new validator http://vefa.difi.no/validator2/ but I am not sure where to report this-

**Comment by SiwMeckelborg** [comment]
Yes, validator2 is based on the master repository, and this rule is not changed 1. july. As it is a warning, we took the decision to do the change in the VA for the release in October, since the revision 1. july was cancelled.

**Comment by tyskjohan** [comment]
Maybe it would be useful to split upt the rule into

    not(count(//cbc:*[not(normalize-space())]) > 0)
(No leaf elements without text content)


and

    not(count(//cac:*[count(*) = 0]) > 0)
(No branch elements without leaves)

Checking for branch (cac:) elements with text is probably not needed as this is covered by the schema itself.

**Comment by SiwMeckelborg** [comment]
Fixed, empty elements and comments only will generate error, and compact xml will not generate error
