### ISSUE TITLE
CEN BII (& Peppol) validation artificates have floating point issues that can result in false positives validation errors

### ISSUE THREAD

**Issue by ThomasDekeyser** [difi/vefa-validator-conf#93]
Problem: 
In XSLT1.0, 30.0000 + 6.645 = 36.644999999999996
In XSLT1.0,  2.0 - 1.1 = 0.8999999999999999
Rounded with 2 decimals => 36.64
Expected result => 36.65

Result: As the existing validation engine is based on validation artifacts released by CEN BII & Peppol, false positives will pop-up.

Possible solution:
* Change all CEN BII (& Peppol) rule artificates so they use XLST2.0 provided xs:decimal(.) constructor. If we do this our self, we will have to do this over & over again whenever those rules are updated. :(

Reference
CEN BII schematron validation artifacts: http://spec.cenbii.eu/Tools/TestConformance.html
Rounding problems in XSLT1.0: http://stackoverflow.com/questions/12746624/number-rounding-and-precision-problems-in-xslt-1-0 
xs:decimal() versus number() versus xs:double() : http://stackoverflow.com/questions/14602878/what-the-difference-between-xsdecimal-and-number-in-xslt-2

**Comment by SiwMeckelborg** [comment]
I have reported this issue to PEPPOL, so this can be evaluated there.

**Comment by SiwMeckelborg** [comment]
I have now looked into this case in more detail. And the problem here is that the //cac:InvoiceLine/cbc:LineExtensionAmount is not rounded. LineExtensionAmount MUST be rounded to 2 decimals since this amount is subject for bookkeeping. See further information on rounding in the implementation guide chapter 6.4.1

**Comment by ThomasDekeyser** [comment]
Thanks for the feedback.
Could you give an URL of that "implementation guide / chapter 6.4.1" ?

In the Peppol BIS4A standard i do find the following
{ref 20140301-PEPPOL_BIS_4A-400.pdf > 10.2.11 Rounding}
 * Rounding shall, as a general rule, be performed on the final result of a calculation only and not on any intermediate calculation, for the result to be mathematically correct.
* Rounding shall result in a decimal figure with two decimal places. The third decimal digit being greater than 4 increases the second decimal digit with 1, whilst the third decimal digit being less than 5 leaves the second decimal digit as it is.
* All amounts on the header level should have a maximum of 2 decimal places. Calculated amounts with more than 2 decimal places, like most VAT calculations, must be rounded. Results from calculations involving already rounded amounts are not subject to rounding, like payable amounts and total amounts included VAT.
{ref}

FYI: I'm mapping telecom invoices, and for those, prices & lineamounts with up to 4 digits are a must have.

**Comment by SiwMeckelborg** [comment]
I am referring to the norwegian EHF Implemantation Guide which you can find here on github:https://github.com/difi/vefa-validator-conf/tree/master/STANDARD/EHFInvoice/2.0/guide

But the same paragraph can also be found in the PEPPOL BIS, as these rules are "inherited" from PEPPOL to EHF. In the PEPPOL BIS, you´ll find the same descriptions in chapter 10.2.11.1 - Elements that must be rounded.

**Comment by SiwMeckelborg** [comment]
Connected to issue #55
