### ISSUE TITLE
Rule EUGEN-T10-R042 raised when rounding is correct

### ISSUE THREAD

**Issue by SiwMeckelborg** [difi/vefa-validator-conf#94]
We have received a report that the rule EUGEN-T10-R042 is fired in situations where it shouldn´t have fired. Example is a VAT Taxable amount of 1280.62 and 25% VAT.  The calculation gives the result of 320.155 and TaxAmount should then be rounded to 320.16. 

However the xpath calculation in the validation artefacts gives the result of 320.15499999999996 and rounded this is 320.15. 

This issue will be discussed in a development team meeting on Thursday 11th June, and result will be reported on this issue.

**Comment by ThomasDekeyser** [comment]
From technical point of view this issue has the same root-cause as [#93]: floating-point issues when doing calculation in xslt1.0

**Comment by SiwMeckelborg** [comment]
Unfortunately the meeting yesterday was postponed till Tuesday, so I cannot give the solution before we have had this meeting.

**Comment by cdruschk** [comment]
Is the test validator page https://test-vefa.difi.no/validator/  updated with the fix for this issue?

**Comment by Lamisi** [comment]
I am experiencing this issue now. How do I go about implent a fix for this?

**Comment by SiwMeckelborg** [comment]
In test or prod, and can you send me the link to the validation that fails (copy the url after you have done the validation), so I can use it for testing?

**Comment by Lamisi** [comment]
I mean, how do I update my files in my applications with the correct
version of your files?

**Comment by SiwMeckelborg** [comment]
If you use the master branch, you will get the latest changes. This revision was released in october:
https://vefa.difi.no/ehf/announcement/2015-10-15-release-available/

**Comment by Lamisi** [comment]
I got a problem with UBL-T10-BiiRules.xsl

Error on line 33 column 71 of UBL-T10-BiiRules.xsl:
  SXXP0003: Error reported by XML parser: Attribute name
"data-pjax-transient" associated
  with an element type "meta" must be followed by the ' = ' character.

**Comment by SiwMeckelborg** [comment]
I see that you have sent an email to the github address, please add any questions here, so the issue can be followed by others & we have a correct log on the issue.
