### ISSUE TITLE
DocumentType specification between EHF & Peppol not inline when sending pdf-version as attachment.

### ISSUE THREAD

**Issue by ThomasDekeyser** [difi/vefa-validator-conf#97]
EHF, Implementation Guide EHF Invoicing Process v2.0.pdf, march 01, 2015, chapter 6.11
If, however, the “pdf-version” is supplied as an attachment, the element “DocumentType” must specify “Commercial invoice” for an invoice and “Credit note” for a creditnote.

Peppol BIS4A, 20140301-PEPPOL_BIS_4A-400.pdf, version 4.00, chapter
If, however, the “pdf-version” is supplied as an attachment, the element “DocumentType” must specify “CommercialInvoice”.

So “Commercial invoice” versus “CommercialInvoice”.  Remark the space & upper/lowercase.
Issue in EHF or Peppol specs?

**Comment by juskoljo** [comment]
Is this going to be fixed/changes in EHF 2.0.5? What IS the actual change? There doesn't seem to be anything changed in latest EHF 2.0.5 implementation guide.

**Comment by juskoljo** [comment]
@SiwMeckelborg any comments?

**Comment by SiwMeckelborg** [comment]
This is a PEPPOL issue, and should not generate any changes to EHF.

**Comment by juskoljo** [comment]
Ok, so that means EHF doesn't follow PeppolBIS specifications on this?

**Comment by SiwMeckelborg** [comment]
This means that the issue will be raised to openPEPPOL, to change this in the PEPPOL BIS specification.

**Comment by juskoljo** [comment]
Sorry, but I don't follow now... :). I thought the initial question was regarding the writing style of commercial invoice, in EHF guide it's "Commercial invoice" and in PeppolBIS it's "CommercialInvoice" (without whitespace as word separator)

It this defined in lower level in UBL as "Commercial invoice"?

**Comment by SiwMeckelborg** [comment]
I am not sure I understand your question/remark, but, this has nothing to do with UBL. This is a recommondation on how to state that the attachement is a commercial invoice, and not something else. This "code"/value is not coming from UBL but from openPEPPOL, and we will raise this as an issue to change the wording in the PEPPOL BIS to state "Commercial invoice".

**Comment by juskoljo** [comment]
Maybe I just didn't express myself clear enough, sorry about that :). Yes, I understand the purpose of this element and value. I'm just trying to figure out is the issue really in PeppolBIS but not in EHF? I've been in impression that EHF follow PeppolBIS specifications, not vice versa.

If this really is the case all the other formats extended from PeppolBIS (like EHF) is doing this wrong too.

**Comment by SiwMeckelborg** [comment]
Yes the purpose is to follow the PEPPOL BIS specifications in EHF, but we will, as I stated previously raise this as an issue to openPEPPOL, to try to make a change in the PEPPOL BIS specification.

**Comment by juskoljo** [comment]
Ok, thanks for the clarification! :)
