### ISSUE TITLE
EHF, Implementation Guide EHF Invoicing chapter 6.5

### ISSUE THREAD

**Issue by joerahol** [difi/vefa-validator-conf#99]
EHF, Implementation Guide EHF Invoicing chapter 6.5

“The customer contact, known as “ Deres ref” in Norwegian, is mandatory. The element is used for the reference of who ordered the products/services. Example being the name of the person ordering, employee number or a code identifying this person or department/group. If this information is not relevant for the invoice, the value “NA” (Not Applicable) should be used.”

How is it possible for the sender to decide if this is applicable for the receiver or not. I am worried that this will be a problem for the receiver, as they will get more invoices for manual handling, as required routing information is missing. In my opinion, NA should never be allowed used. Having said that, if customers order number is returned on the invoice, the customer contact will not be used for routing, as the invoice will be routed and matched based on the order number. It is better to have too many references, then allowing NA to be used. 

Regards
Per Martin Jøraholmen
Head of section
DFØ

**Comment by SiwMeckelborg** [comment]
In B2B scenarios (and other as well) this information might very well not be in use, as it is the order-number that is used. Several businesses have a policy to approve the order before the purchase, and then the invoice is automatically handled when the order and invoice match. In these scenarios there is no need for "your ref". Today we see that there is several ways of handling this, sending a space, a . or - or some other character. It is then better to use the value NA, as it clearly states that this information is not applicable.

**Comment by joerahol** [comment]
As I wrote in my comment, we also don’t use “your ref” if order number is returned. The sender cannot know if the receiver is using the “your ref” or the order number for routing and invoice matching. We also see that “your ref” contains . – “space” and so on. In these occasions, we send and automatic email back to the sender, asking him to correct by the next invoicing. If NA becomes a allowed entry, we cannot inform the sender to correct. Again, how can the sender know if this is not applicable for the receiver? It is better to have too many references than too few.

**Comment by SiwMeckelborg** [comment]
It is the recipient who decides what to put in "your ref" and should inform the issuer of what information they need in this element. If the recipient do not need this, because, as an example they use the order number, the value should be stated as NA.

**Comment by joerahol** [comment]
The people that do purchasing, I think, does not have the technical understanding of EHF, or the purchasing/invoicing/ERP system too  inform suppliers that “your ref” is not needed for one supplier, but needed by an other.
By the way, every one can send us an invoice, without being in contact with us.
 “Your ref” should always be used with a valid content, regardless if the receiver needs this or not.
